### ISSUE TITLE
s/reserach/research/

### ISSUE THREAD

**Issue by stevenjowens** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#22]
"The AprilTags project originates from a team at the University of Michigan, that has a detailed website dedicated to the reserach,"

http://roboticsknowledgebase.com/wiki/sensing/apriltags/

**Comment by smbryan** [comment]
Caught a few more typos too.  Fixed in 8e85e5d4da5fd0f02d8211aee0ccc1c76401b65d.
