### ISSUE TITLE
UMich April Tags project URL

### ISSUE THREAD

**Issue by stevenjowens** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#23]
http://roboticsknowledgebase.com/wiki/sensing/apriltags/

"The AprilTags project originates from a team at the University of Michigan, that has a detailed website dedicated to the reserach,"

(Note, already opened a separate issue for the typo in "reserach", https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/issues/22)

The phrase "detailed website dedicated to the reserach" links to:

https://april.eecs.umich.edu/wiki/AprilTags

That page contains only the text:

"AprilTags
(Redirected from Index.php/AprilTags)
The latest version of AprilTag can be found at https://april.eecs.umich.edu/apriltag/"

**Comment by smbryan** [comment]
Thanks for catching that. Fixed in 8e85e5d4da5fd0f02d8211aee0ccc1c76401b65d.
