### ISSUE TITLE
Gaussian Process for Regression Math Rendering

### ISSUE THREAD

**Issue by smbryan** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#64]
@yshi329, some of the formulas in the GP for Regression isn't rendering correctly. Should be a quick fix.

**Comment by heethesh** [comment]
@smbryan looks like MathJax is not rendering on other articles as well ([example](https://roboticsknowledgebase.com/wiki/state-estimation/radar-camera-sensor-fusion/#motion-compensation-of-tracks))

**Comment by heethesh** [comment]
PR #81

**Comment by smbryan** [comment]
@heethesh, your last PR did the trick. Well done.
