### ISSUE TITLE
Enable HTTPS in github pages

### ISSUE THREAD

**Issue by t27** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#66]
This is Tarang from the MRSD 2020 batch,

Github has added free HTTPS certificated for Github Pages websites, we can enable that on this site to ensure that the site doesnt show up as "Not Secure" in chrome and maintain the authenticity and visibility in google searches.

![image](https://user-images.githubusercontent.com/2003371/73234054-830ece80-4156-11ea-85b4-7bc8600423a3.png)

This link has the procedure, have previously used it for one of my custom websites and have had not issues with this

https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by smbryan** [comment]
@t27, that's an excellent idea. However, it will require some additional work since we're using a custom domain name, but not too much. I'll tackle this shortly.

**Comment by t27** [comment]
Yes, for CNAME or ALIAS type domains its pretty seamless as Github takes care of the LetsEncrypt certificate and its renewal and they allow you to enforce https for auto redirects as well
https://github.blog/2018-05-01-github-pages-custom-domains-https/

Thanks!

**Comment by smbryan** [comment]
We're up on HTTPS. Thanks again for bringing this to my attention.

**Comment by t27** [comment]
Hey Bryan!
Thanks,
The site does redirect and i can see the https url in my address bar, but for some reason the site isn't loading the content. It says page not found.
