### ISSUE TITLE
A small typo in gaussian-process-gaussian-mixture-model

### ISSUE THREAD

**Issue by LiyuanHsu** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#82]
@heethesh In `gaussian-process-gaussian-mixture-model.md`, `\( \alpha_k \)is the probability that the observed data is from the \( k \)th gaussian, \( \alpha_k > 0 \), \( \Sigma_{k=1}^{N}\alpha_k=1 \)`: the summation range for alpha_k should be from 1 to K, I guess.

**Comment by heethesh** [comment]
Fixed, thanks!
