### ISSUE TITLE
Please do not recommend ur_driver nor ur_modern_driver

### ISSUE THREAD

**Issue by gavanderhoorn** [RoboticsKnowledgebase/roboticsknowledgebase.github.io#83]
The [actuation/ur5e-control.md](https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/blob/f3c5fd4f6d239a5a724205935ec750ac9254473f/wiki/actuation/ur5e-control.md) page appears to recommend users use either `ur_driver` or `ur_modern_driver` for use with a UR robot controller.

Both those packages have been deprecated for quite some time now. See [Deprecation of ur_modern_driver](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629) fi.

It would be best not to tell people to use those packages, and instead rewrite the tutorial to use [UniversalRobots/Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver), which is the only officially supported ROS driver for Universal Robots.

**Comment by gavanderhoorn** [comment]
Note: the tutorial on the ROS wiki which is linked in the *References* section ([this one](http://wiki.ros.org/universal_robot/Tutorials/Getting%20Started%20with%20a%20Universal%20Robot%20and%20ROS-Industrial)) has had a notice showing it is deprecated and should not be followed any more since June.

**Comment by smbryan** [comment]
@gavanderhoorn, thank you for bringing this to our attention. I've removed the article for the time being.

We'll see if any student projects are using the UR arm that could update it.

**Comment by gavanderhoorn** [comment]
Thank you.
